.ORIG x3000

LD R6, INITIALIZE

LD R1, INTERRUPTVECTOR
LD R2, INTSR
STI R2, INTERRUPTVECTOR

STR R2, R1, #0
LDI R3, KBSR
LD R4, IE
STI R4, KBSR


START	LEA R0, LINE1
	PUTS
	LD R0, NL
	OUT	
	JSR DELAY
START2	LEA R0, LINE2
	PUTS
	LD R0, NL
	OUT	
	JSR DELAY
	BRnzp START




HALT
LINE1	.stringz "UT    UT    UT    UT    UT    UT    UT    UT    "
LINE2	.stringz "   UT    UT    UT    UT    UT    UT    UT    "
NL	.FILL x000A
WHICHLN	.FILL x0000
DELAY   ST  R1, SaveR1
        LD  R1, COUNT
REP     ADD R1,R1,#-1
        BRp REP
        LD  R1, SaveR1
        RET
COUNT   .FILL #2500
SaveR1  .BLKW 1
INITIALIZE	.FILL x3000
INTSR	.FILL x2000
INTERRUPTVECTOR  .FILL x0180
KBSR	.FILL xFE00
KBDR	.FILL xFE02
IE	.FILL x4000
.END